In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/mohdsalib/Downloads/rz_master_subdiv.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30194 entries, 0 to 30193
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            30194 non-null  int64
 1   Organisation  30192 non-null  object
 2   Department    19069 non-null  object
dtypes: int64(1), object(2)
memory usage: 707.8+ KB

In [4]:
df.head()

   id                 Organisation               Department
0   1  Airports Authority of India     Western Region - AAI
1   1  Airports Authority of India  North East Region - AAI
2   1  Airports Authority of India     Eastern Region - AAI
3   1  Airports Authority of India    Southern Region - AAI
4   1  Airports Authority of India    Northern Region - AAI

In [5]:
df.describe(include='all')

                  id          Organisation Department
count   30194.000000                 30192      19069
unique           NaN                 12898      17252
top              NaN  Government of Kerala     STORES
freq             NaN                  1127         26
mean     7899.772935                   NaN        NaN
std     12920.722226                   NaN        NaN
min         1.000000                   NaN        NaN
25%      1025.000000                   NaN        NaN
50%      4218.000000                   NaN        NaN
75%      8253.750000                   NaN        NaN
max     57449.000000                   NaN        NaN

In [6]:
df['Organisation'].head(20)

0                           Airports Authority of India
1                           Airports Authority of India
2                           Airports Authority of India
3                           Airports Authority of India
4                           Airports Authority of India
5                           Airports Authority of India
6        Department of Defence Research and Development
7        Department of Defence Research and Development
8        Department of Defence Research and Development
9                     AGRICULTURE PRODUCTION DEPARTMENT
10                    AGRICULTURE PRODUCTION DEPARTMENT
11                    AGRICULTURE PRODUCTION DEPARTMENT
12                    AGRICULTURE PRODUCTION DEPARTMENT
13                                              MIDHANI
14    Directorate of Information Technology and Comm...
15                                       Daman District
16                                       Daman District
17                                       Daman District
18                                       Daman District
19                                       Daman District
Name: Organisation, dtype: object

In [7]:
df['location_raw'] = df['Organisation'].astype(str)

In [8]:
df['location_raw'] = df['location_raw'].str.replace('-', ',', regex=False)

In [9]:
df['location_raw'] = df['location_raw'].str.split(',').str[-1]

In [10]:
df['location_raw'] = df['location_raw'].str.strip()

In [11]:
df[['Organisation', 'location_raw']].head(20)

,Organisation,location_raw
0,Airports Authority of India,Airports Authority of India
1,Airports Authority of India,Airports Authority of India
2,Airports Authority of India,Airports Authority of India
3,Airports Authority of India,Airports Authority of India
4,Airports Authority of India,Airports Authority of India
5,Airports Authority of India,Airports Authority of India
6,Department of Defence Research and Development,Department of Defence Research and Development
7,Department of Defence Research and Development,Department of Defence Research and Development
8,Department of Defence Research and Development,Department of Defence Research and Development
9,AGRICULTURE PRODUCTION DEPARTMENT,AGRICULTURE PRODUCTION DEPARTMENT
10,AGRICULTURE PRODUCTION DEPARTMENT,AGRICULTURE PRODUCTION DEPARTMENT
11,AGRICULTURE PRODUCTION DEPARTMENT,AGRICULTURE PRODUCTION DEPARTMENT
12,AGRICULTURE PRODUCTION DEPARTMENT,AGRICULTURE PRODUCTION DEPARTMENT
13,MIDHANI,MIDHANI
14,Directorate of Information Technology and Comm...,Directorate of Information Technology and Comm...
15,Daman District,Daman District
16,Daman District,Daman District
17,Daman District,Daman District
18,Daman District,Daman District
19,Daman District,Daman District

In [12]:
df['location_clean'] = df['location_raw'].str.lower()

In [13]:
bad_words = [
    'division', 'engineer', 'project', 'unit', 'office',
    'department', 'dept', 'circle', 'zone'
]

In [14]:
import numpy as np

df['location_clean'] = df['location_clean'].apply(
    lambda x: np.nan if any(word in x for word in bad_words) else x
)

In [15]:
df['location_clean'] = df['location_clean'].apply(
    lambda x: np.nan if isinstance(x, str) and len(x.split()) > 3 else x
)

In [16]:
df['location_clean'] = df.apply(
    lambda row: row['location_clean'] 
    if (',' in str(row['Organisation']) or '-' in str(row['Organisation'])) 
    else np.nan,
    axis=1
)

In [17]:
df['location_extracted'] = df['location_clean'].str.title()

In [18]:
df[['Organisation', 'location_raw', 'location_extracted']].head(95)

,Organisation,location_raw,location_extracted
0,Airports Authority of India,Airports Authority of India,NaN
1,Airports Authority of India,Airports Authority of India,NaN
2,Airports Authority of India,Airports Authority of India,NaN
3,Airports Authority of India,Airports Authority of India,NaN
4,Airports Authority of India,Airports Authority of India,NaN
...,...,...,...
90,"Chief Engineer, PWD (DWS)",PWD (DWS),Pwd (Dws)
91,"Chief Engineer, PWD (DWS)",PWD (DWS),Pwd (Dws)
92,"Chief Engineer, PWD (DWS)",PWD (DWS),Pwd (Dws)
93,CE-PWD(B and R),PWD(B and R),Pwd(B And R)
94,CE-PWD(B and R),PWD(B and R),Pwd(B And R)

In [19]:
import numpy as np

df['location_clean'] = df['location_clean'].apply(
    lambda x: np.nan if isinstance(x, str) and ('(' in x or ')' in x) else x
)

In [20]:
df[['Organisation', 'location_raw', 'location_clean']].head(549)

,Organisation,location_raw,location_clean
0,Airports Authority of India,Airports Authority of India,NaN
1,Airports Authority of India,Airports Authority of India,NaN
2,Airports Authority of India,Airports Authority of India,NaN
3,Airports Authority of India,Airports Authority of India,NaN
4,Airports Authority of India,Airports Authority of India,NaN
...,...,...,...
544,Chief Engineer PWD (DWS)-Tripura,Tripura,tripura
545,Chief Engineer PWD (DWS)-Tripura,Tripura,tripura
546,Chief Engineer PWD (DWS)-Tripura,Tripura,tripura
547,Cochin Port Trust,Cochin Port Trust,NaN
548,Cochin Port Trust,Cochin Port Trust,NaN

In [21]:
df['location_extracted'] = df['location_clean'].str.title()

In [22]:
df[['Organisation', 'location_clean', 'location_extracted']].head(50)

,Organisation,location_clean,location_extracted
0,Airports Authority of India,NaN,NaN
1,Airports Authority of India,NaN,NaN
2,Airports Authority of India,NaN,NaN
3,Airports Authority of India,NaN,NaN
4,Airports Authority of India,NaN,NaN
5,Airports Authority of India,NaN,NaN
6,Department of Defence Research and Development,NaN,NaN
7,Department of Defence Research and Development,NaN,NaN
8,Department of Defence Research and Development,NaN,NaN
9,AGRICULTURE PRODUCTION DEPARTMENT,NaN,NaN
10,AGRICULTURE PRODUCTION DEPARTMENT,NaN,NaN
11,AGRICULTURE PRODUCTION DEPARTMENT,NaN,NaN
12,AGRICULTURE PRODUCTION DEPARTMENT,NaN,NaN
13,MIDHANI,NaN,NaN
14,Directorate of Information Technology and Comm...,NaN,NaN
15,Daman District,NaN,NaN
16,Daman District,NaN,NaN
17,Daman District,NaN,NaN
18,Daman District,NaN,NaN
19,Daman District,NaN,NaN
20,Daman District,NaN,NaN
21,Daman District,NaN,NaN
22,Daman District,NaN,NaN
23,Daman District,NaN,NaN
24,Daman District,NaN,NaN
25,Daman District,NaN,NaN
26,Daman District,NaN,NaN
27,Daman District,NaN,NaN
28,Daman District,NaN,NaN
29,Daman District,NaN,NaN
30,Daman District,NaN,NaN
31,Daman District,NaN,NaN
32,Daman District,NaN,NaN
33,Daman District,NaN,NaN
34,Daman District,NaN,NaN
35,Daman District,NaN,NaN
36,"CPCL,DGM(M and C)",NaN,NaN
37,"CPCL,DGM(M and C)",NaN,NaN
38,"CPCL,DGM(M and C)",NaN,NaN
39,"CPCL,DGM(M and C)",NaN,NaN
40,"CPCL,DGM(M and C)",NaN,NaN
41,"CPCL,DGM(M and C)",NaN,NaN
42,"CPCL,DGM(M and C)",NaN,NaN
43,"CPCL,DGM(M and C)",NaN,NaN
44,Civil Aviation,NaN,NaN
45,CE-MRRDA,mrrda,Mrrda
46,CE-MRRDA,mrrda,Mrrda
47,CE-MRRDA,mrrda,Mrrda
48,CE-MRRDA,mrrda,Mrrda
49,CE-MRRDA,mrrda,Mrrda

In [23]:
df['location_clean'] = df['location_clean'].apply(
    lambda x: np.nan 
    if isinstance(x, str) and x.isupper() and len(x) <= 6 
    else x
)

In [24]:
df[['Organisation', 'location_clean', 'location_extracted']].head(7959)

,Organisation,location_clean,location_extracted
0,Airports Authority of India,NaN,NaN
1,Airports Authority of India,NaN,NaN
2,Airports Authority of India,NaN,NaN
3,Airports Authority of India,NaN,NaN
4,Airports Authority of India,NaN,NaN
...,...,...,...
7954,RCDF- MD,md,Md
7955,RCDF- MD,md,Md
7956,RCDF- MD,md,Md
7957,RCDF- MD,md,Md
7958,SOUTH BENGAL STATE TRANSPORT CORPORATION,NaN,NaN

In [25]:
valid_locations = [
    "delhi", "bihar", "rajasthan", "mumbai", "chennai",
    "kolkata", "karnataka", "uttar pradesh", "up",
    "mp", "maharashtra", "gujarat", "punjab", "haryana",
    "jaipur", "hyderabad", "bangalore"
]

In [26]:
df['location_clean'] = df['location_clean'].apply(
    lambda x: x if isinstance(x, str) and (len(x) > 5 or x in valid_locations) else np.nan
)

In [27]:
df[['Organisation', 'location_clean', 'location_extracted']].head(30170)

,Organisation,location_clean,location_extracted
0,Airports Authority of India,NaN,NaN
1,Airports Authority of India,NaN,NaN
2,Airports Authority of India,NaN,NaN
3,Airports Authority of India,NaN,NaN
4,Airports Authority of India,NaN,NaN
...,...,...,...
30165,STATE WAREHOUSING CORPORATION-General Manager ...,NaN,NaN
30166,Kasaba Vividhodhesha Prathamika Gramina Krushi...,NaN,NaN
30167,R&B - Telangana-EE OFFICE-MAHABUBNAGAR,mahabubnagar,Mahabubnagar
30168,State Election Commission NCT of UT Chandigarh,NaN,NaN
30169,PROF JAYASHANKAR TS AGRICULTURAL UNIVERSITY-Es...,NaN,NaN

In [28]:
df['org_clean'] = df['Organisation']

In [29]:
df['org_clean'] = df['org_clean'].str.lower()

In [30]:
df['org_clean'] = df['org_clean'].str.replace(r'[^a-z0-9\s]', '', regex=True)

In [31]:
df['org_clean'] = df['org_clean'].str.strip()
df['org_clean'] = df['org_clean'].str.replace(r'\s+', ' ', regex=True)

In [32]:
df[['Organisation', 'org_clean']].head(600)

,Organisation,org_clean
0,Airports Authority of India,airports authority of india
1,Airports Authority of India,airports authority of india
2,Airports Authority of India,airports authority of india
3,Airports Authority of India,airports authority of india
4,Airports Authority of India,airports authority of india
...,...,...
595,E-IN-C BRANCH - MILITARY ENGINEER SERVICES,einc branch military engineer services
596,E-IN-C BRANCH - MILITARY ENGINEER SERVICES,einc branch military engineer services
597,E-IN-C BRANCH - MILITARY ENGINEER SERVICES,einc branch military engineer services
598,E-IN-C BRANCH - MILITARY ENGINEER SERVICES,einc branch military engineer services
599,Cochin Shipyard Limited,cochin shipyard limited

In [33]:
noise_words = [
    "department", "dept", "office", "division", "unit", "cell",
    "circle", "region", "regional", "ro",
    "chief", "engineer", "executive", "superintending",
    "government", "of", "the", "and"
]

In [34]:
df['org_clean'] = df['org_clean'].apply(
    lambda x: ' '.join([word for word in str(x).split() if word not in noise_words]) if pd.notnull(x) else x
)

In [35]:
noise_words = [word.lower() for word in noise_words]

In [36]:
df['org_clean'] = df['org_clean'].apply(
    lambda x: ' '.join(
        [word for word in str(x).lower().split() if word not in noise_words]
    ) if pd.notnull(x) else x
)

In [37]:
df[['Organisation', 'org_clean']].head(30)

,Organisation,org_clean
0,Airports Authority of India,airports authority india
1,Airports Authority of India,airports authority india
2,Airports Authority of India,airports authority india
3,Airports Authority of India,airports authority india
4,Airports Authority of India,airports authority india
5,Airports Authority of India,airports authority india
6,Department of Defence Research and Development,defence research development
7,Department of Defence Research and Development,defence research development
8,Department of Defence Research and Development,defence research development
9,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production
10,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production
11,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production
12,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production
13,MIDHANI,midhani
14,Directorate of Information Technology and Comm...,directorate information technology communication
15,Daman District,daman district
16,Daman District,daman district
17,Daman District,daman district
18,Daman District,daman district
19,Daman District,daman district
20,Daman District,daman district
21,Daman District,daman district
22,Daman District,daman district
23,Daman District,daman district
24,Daman District,daman district
25,Daman District,daman district
26,Daman District,daman district
27,Daman District,daman district
28,Daman District,daman district
29,Daman District,daman district

In [38]:
org_map = {
    "nhai": "NHAI",
    "national highways authority": "NHAI",
    
    "airports authority": "AAI",
    "aai": "AAI",
    
    "indian railways": "Indian Railways",
    "railway": "Indian Railways",
    
    "pwd": "PWD",
    
    "municipal": "Municipal Corporation",
    "municipal corporation": "Municipal Corporation"
}

In [39]:
def map_org(x):
    if pd.isnull(x):
        return x
    
    for key in org_map:
        if key in x:
            return org_map[key]
    
    return x

In [40]:
df['org_final'] = df['org_clean'].apply(map_org)

In [41]:
df[['Organisation', 'org_clean', 'org_final']].head(50)

,Organisation,org_clean,org_final
0,Airports Authority of India,airports authority india,AAI
1,Airports Authority of India,airports authority india,AAI
2,Airports Authority of India,airports authority india,AAI
3,Airports Authority of India,airports authority india,AAI
4,Airports Authority of India,airports authority india,AAI
5,Airports Authority of India,airports authority india,AAI
6,Department of Defence Research and Development,defence research development,defence research development
7,Department of Defence Research and Development,defence research development,defence research development
8,Department of Defence Research and Development,defence research development,defence research development
9,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production,agriculture production
10,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production,agriculture production
11,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production,agriculture production
12,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production,agriculture production
13,MIDHANI,midhani,midhani
14,Directorate of Information Technology and Comm...,directorate information technology communication,directorate information technology communication
15,Daman District,daman district,daman district
16,Daman District,daman district,daman district
17,Daman District,daman district,daman district
18,Daman District,daman district,daman district
19,Daman District,daman district,daman district
20,Daman District,daman district,daman district
21,Daman District,daman district,daman district
22,Daman District,daman district,daman district
23,Daman District,daman district,daman district
24,Daman District,daman district,daman district
25,Daman District,daman district,daman district
26,Daman District,daman district,daman district
27,Daman District,daman district,daman district
28,Daman District,daman district,daman district
29,Daman District,daman district,daman district
30,Daman District,daman district,daman district
31,Daman District,daman district,daman district
32,Daman District,daman district,daman district
33,Daman District,daman district,daman district
34,Daman District,daman district,daman district
35,Daman District,daman district,daman district
36,"CPCL,DGM(M and C)",cpcldgmm c,cpcldgmm c
37,"CPCL,DGM(M and C)",cpcldgmm c,cpcldgmm c
38,"CPCL,DGM(M and C)",cpcldgmm c,cpcldgmm c
39,"CPCL,DGM(M and C)",cpcldgmm c,cpcldgmm c
40,"CPCL,DGM(M and C)",cpcldgmm c,cpcldgmm c
41,"CPCL,DGM(M and C)",cpcldgmm c,cpcldgmm c
42,"CPCL,DGM(M and C)",cpcldgmm c,cpcldgmm c
43,"CPCL,DGM(M and C)",cpcldgmm c,cpcldgmm c
44,Civil Aviation,civil aviation,civil aviation
45,CE-MRRDA,cemrrda,cemrrda
46,CE-MRRDA,cemrrda,cemrrda
47,CE-MRRDA,cemrrda,cemrrda
48,CE-MRRDA,cemrrda,cemrrda
49,CE-MRRDA,cemrrda,cemrrda

In [42]:
df['org_clean'].value_counts().head(20)

org_clean
kerala                                            1127
directorate local bodies up                        764
higher education                                   566
bihar                                              250
urban administration development uadd              194
maws                                               172
northern rly                                       153
directorate health services                        146
municipal corporation greater mumbai               140
health family welfare                              130
western rly                                        129
central rly                                        118
ministry external affairs                          117
southern rly                                       110
municipal bodies                                   107
haryana                                            102
director general prisons correctional services     102
vadodara municipal corporation                     101
engineerinchief water resources                     97
east central rly                                    95
Name: count, dtype: int64

In [43]:
location_words = [
    "kerala", "bihar", "haryana", "delhi", "rajasthan",
    "maharashtra", "gujarat", "punjab", "up", "mp"
]

In [44]:
df['org_clean'] = df['org_clean'].apply(
    lambda x: np.nan if x in location_words else x
)

In [45]:
df['org_clean'].value_counts().head(20)

org_clean
directorate local bodies up                       764
higher education                                  566
urban administration development uadd             194
maws                                              172
northern rly                                      153
directorate health services                       146
municipal corporation greater mumbai              140
health family welfare                             130
western rly                                       129
central rly                                       118
ministry external affairs                         117
southern rly                                      110
municipal bodies                                  107
director general prisons correctional services    102
vadodara municipal corporation                    101
engineerinchief water resources                    97
east central rly                                   95
south central rly                                  93
odisha power transmission corporation limited      91
university rajasthan                               91
Name: count, dtype: int64

In [46]:
df['org_search'] = df['org_clean'].fillna('') + " " + df['org_final'].fillna('')

In [47]:
df['org_search'] = df['org_search'].str.lower()
df['org_search'] = df['org_search'].str.replace(r'\s+', ' ', regex=True)
df['org_search'] = df['org_search'].str.strip()

In [48]:
df[['Organisation', 'org_final', 'org_search']].head(30)

,Organisation,org_final,org_search
0,Airports Authority of India,AAI,airports authority india aai
1,Airports Authority of India,AAI,airports authority india aai
2,Airports Authority of India,AAI,airports authority india aai
3,Airports Authority of India,AAI,airports authority india aai
4,Airports Authority of India,AAI,airports authority india aai
5,Airports Authority of India,AAI,airports authority india aai
6,Department of Defence Research and Development,defence research development,defence research development defence research ...
7,Department of Defence Research and Development,defence research development,defence research development defence research ...
8,Department of Defence Research and Development,defence research development,defence research development defence research ...
9,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production,agriculture production agriculture production
10,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production,agriculture production agriculture production
11,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production,agriculture production agriculture production
12,AGRICULTURE PRODUCTION DEPARTMENT,agriculture production,agriculture production agriculture production
13,MIDHANI,midhani,midhani midhani
14,Directorate of Information Technology and Comm...,directorate information technology communication,directorate information technology communicati...
15,Daman District,daman district,daman district daman district
16,Daman District,daman district,daman district daman district
17,Daman District,daman district,daman district daman district
18,Daman District,daman district,daman district daman district
19,Daman District,daman district,daman district daman district
20,Daman District,daman district,daman district daman district
21,Daman District,daman district,daman district daman district
22,Daman District,daman district,daman district daman district
23,Daman District,daman district,daman district daman district
24,Daman District,daman district,daman district daman district
25,Daman District,daman district,daman district daman district
26,Daman District,daman district,daman district daman district
27,Daman District,daman district,daman district daman district
28,Daman District,daman district,daman district daman district
29,Daman District,daman district,daman district daman district

In [49]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [50]:
import os
os.path.expanduser("~")

'/Users/mohdsalib'

In [51]:
df.astype(str).to_csv(os.path.expanduser("/Users/mohdsalib/Downloads/cleaned_data.csv"), index=False, encoding='utf-8-sig')

In [52]:
df.head()

,id,Organisation,Department,location_raw,location_clean,location_extracted,org_clean,org_final,org_search
0,1,Airports Authority of India,Western Region - AAI,Airports Authority of India,NaN,NaN,airports authority india,AAI,airports authority india aai
1,1,Airports Authority of India,North East Region - AAI,Airports Authority of India,NaN,NaN,airports authority india,AAI,airports authority india aai
2,1,Airports Authority of India,Eastern Region - AAI,Airports Authority of India,NaN,NaN,airports authority india,AAI,airports authority india aai
3,1,Airports Authority of India,Southern Region - AAI,Airports Authority of India,NaN,NaN,airports authority india,AAI,airports authority india aai
4,1,Airports Authority of India,Northern Region - AAI,Airports Authority of India,NaN,NaN,airports authority india,AAI,airports authority india aai

In [53]:
df.drop(columns=["location_clean"], inplace=True)

In [54]:
df.head()

,id,Organisation,Department,location_raw,location_extracted,org_clean,org_final,org_search
0,1,Airports Authority of India,Western Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
1,1,Airports Authority of India,North East Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
2,1,Airports Authority of India,Eastern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
3,1,Airports Authority of India,Southern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
4,1,Airports Authority of India,Northern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai

In [55]:
df.rename(columns={
    "org_clean": "Org Name (Raw)",
    "org_final": "Org Name (Clean)",
    "location_extracted": "Location (clean)",
    "location_raw": "Location (raw)"
}, inplace=True)

In [56]:
df.head()

,id,Organisation,Department,Location (raw),Location (clean),Org Name (Raw),Org Name (Clean),org_search
0,1,Airports Authority of India,Western Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
1,1,Airports Authority of India,North East Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
2,1,Airports Authority of India,Eastern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
3,1,Airports Authority of India,Southern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
4,1,Airports Authority of India,Northern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai

In [57]:
df.to_csv("full_dataset.csv", index=False)

In [58]:
df.head(55)

,id,Organisation,Department,Location (raw),Location (clean),Org Name (Raw),Org Name (Clean),org_search
0,1,Airports Authority of India,Western Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
1,1,Airports Authority of India,North East Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
2,1,Airports Authority of India,Eastern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
3,1,Airports Authority of India,Southern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
4,1,Airports Authority of India,Northern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
5,1,Airports Authority of India,CHQ - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
6,2,Department of Defence Research and Development,Defence Institute of Advanced Technology,Department of Defence Research and Development,NaN,defence research development,defence research development,defence research development defence research ...
7,2,Department of Defence Research and Development,Defence Research and Development Organisation,Department of Defence Research and Development,NaN,defence research development,defence research development,defence research development defence research ...
8,2,Department of Defence Research and Development,Aeronautical Development Agency,Department of Defence Research and Development,NaN,defence research development,defence research development,defence research development defence research ...
9,3,AGRICULTURE PRODUCTION DEPARTMENT,Command Area Development Kashmir,AGRICULTURE PRODUCTION DEPARTMENT,NaN,agriculture production,agriculture production,agriculture production agriculture production
10,3,AGRICULTURE PRODUCTION DEPARTMENT,Command Area Development Jammu,AGRICULTURE PRODUCTION DEPARTMENT,NaN,agriculture production,agriculture production,agriculture production agriculture production
11,3,AGRICULTURE PRODUCTION DEPARTMENT,Agriculture Department Jammu and Kashmir,AGRICULTURE PRODUCTION DEPARTMENT,NaN,agriculture production,agriculture production,agriculture production agriculture production
12,3,AGRICULTURE PRODUCTION DEPARTMENT,Mission Directorate Holistic Agriculture Devel...,AGRICULTURE PRODUCTION DEPARTMENT,NaN,agriculture production,agriculture production,agriculture production agriculture production
13,4,MIDHANI,NaN,MIDHANI,NaN,midhani,midhani,midhani midhani
14,5,Directorate of Information Technology and Comm...,Nagaland State eGovernace Society,Directorate of Information Technology and Comm...,NaN,directorate information technology communication,directorate information technology communication,directorate information technology communicati...
15,6,Daman District,Staff Selection Board - Daman,Daman District,NaN,daman district,daman district,daman district daman district
16,6,Daman District,Public Works Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
17,6,Daman District,Town Planning - Daman,Daman District,NaN,daman district,daman district,daman district daman district
18,6,Daman District,Tourism Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
19,6,Daman District,Omnibus Industrial Development Corporation - D...,Daman District,NaN,daman district,daman district,daman district daman district
20,6,Daman District,Sports Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
21,6,Daman District,Excise - Daman,Daman District,NaN,daman district,daman district,daman district daman district
22,6,Daman District,Medical and Health Dept. - Daman,Daman District,NaN,daman district,daman district,daman district daman district
23,6,Daman District,Jail - Daman,Daman District,NaN,daman district,daman district,daman district daman district
24,6,Daman District,Veterinary Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
25,6,Daman District,Power/Electricity Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
26,6,Daman District,Government Engineering College - Daman,Daman District,NaN,daman district,daman district,daman district daman district
27,6,Daman District,Municipal Council - Daman,Daman District,NaN,daman district,daman district,daman district daman district
28,6,Daman District,Mamlatdar - Daman,Daman District,NaN,daman district,daman district,daman district daman district
29,6,Daman District,Election Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
30,6,Daman District,Collectorate - Daman,Daman District,NaN,daman district,daman district,daman district daman district
31,6,Daman District,IT Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
32,6,Daman District,Fire Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
33,6,Daman District,Police Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
34,6,Daman District,Transport Department - Daman,Daman District,NaN,daman district,daman district,daman district daman district
35,6,Daman District,Planning and Statistics - Daman,Daman District,NaN,daman district,daman district,daman district daman district
36,7,"CPCL,DGM(M and C)",Projects Contracts,DGM(M and C),NaN,cpcldgmm c,cpcldgmm c,cpcldgmm c cpcldgmm c
37,7,"CPCL,DGM(M and C)",CM - CONTRACTS,DGM(M and C),NaN,cpcldgmm c,cpcldgmm c,cpcldgmm c cpcldgmm c
38,7,"CPCL,DGM(M and C)",CM - MATERIALS,DGM(M and C),NaN,cpcldgmm c,cpcldgmm c,cpcldgmm c cpcldgmm c
39,7,"CPCL,DGM(M and C)",Maintenance - Contracts and Estimates,DGM(M and C),NaN,cpcldgmm c,cpcldgmm c,cpcldgmm c cpcldgmm c
40,7,"CPCL,DGM(M and C)",9 CBRP,DGM(M and C),NaN,cpcldgmm c,cpcldgmm c,cpcldgmm c cpcldgmm c
41,7,"CPCL,DGM(M and C)",Projects Materials,DGM(M and C),NaN,cpcldgmm c,cpcldgmm c,cpcldgmm c cpcldgmm c
42,7,"CPCL,DGM(M and C)",Offsite - Maintenance,DGM(M and C),NaN,cpcldgmm c,cpcldgmm c,cpcldgmm c cpcldgmm c
43,7,"CPCL,DGM(M and C)",Financial,DGM(M and C),NaN,cpcldgmm c,cpcldgmm c,cpcldgmm c cpcldgmm c
44,8,Civil Aviation,NaN,Civil Aviation,NaN,civil aviation,civil aviation,civil aviation civil aviation
45,9,CE-MRRDA,SE-5 AURANGABAD,MRRDA,Mrrda,cemrrda,cemrrda,cemrrda cemrrda
46,9,CE-MRRDA,SE-3 NAGPUR,MRRDA,Mrrda,cemrrda,cemrrda,cemrrda cemrrda
47,9,CE-MRRDA,SE-4 AMARAVATI,MRRDA,Mrrda,cemrrda,cemrrda,cemrrda cemrrda
48,9,CE-MRRDA,SE-1 PUNE,MRRDA,Mrrda,cemrrda,cemrrda,cemrrda cemrrda
49,9,CE-MRRDA,SE-2 NASHIK,MRRDA,Mrrda,cemrrda,cemrrda,cemrrda cemrrda
50,9,CE-MRRDA,SE-6 KONKAN,MRRDA,Mrrda,cemrrda,cemrrda,cemrrda cemrrda
51,10,"Er in Chief, Bihar",NaN,Bihar,Bihar,er in bihar,er in bihar,er in bihar er in bihar
52,11,HPPWD,SE 1 Circle Mandi,HPPWD,NaN,hppwd,PWD,hppwd pwd
53,12,DWSD EinC,DWSD CE RANCHI,DWSD EinC,NaN,dwsd einc,dwsd einc,dwsd einc dwsd einc
54,12,DWSD EinC,DWSD CE DUMKA,DWSD EinC,NaN,dwsd einc,dwsd einc,dwsd einc dwsd einc

In [59]:
df.to_csv("full_dataset.csv", index=False, na_rep="NaN")

In [60]:
junk_words = [
    "Mrrda","ce", "lgstpp", "pdd", "mha",
    "prisons", "world bank tenders"
]

df["Location (clean)"] = df["Location (clean)"].apply(
    lambda x: "Nan" if x in junk_words else x
)

In [61]:
df.to_csv("full_dataset.csv", index=False, na_rep="NaN")

In [62]:
import numpy as np

In [63]:
import numpy as np

df["Location (clean)"] = df["Location (clean)"].replace("Unknown", np.nan)

In [64]:
df.to_csv("full_dataset.csv", index=False, na_rep="NaN")

In [71]:
junk_words = [
    "Mrrda","Ce", "Igstpp", "Pdd", "Mha","Adb Tenders", "Roads And Bridges", "Sez Authority", "Electronics And Communications",
    "Prisons", "World Bank Tenders", "Med N Minor", "Mohrd", "Mhfw", "Laxmiposi", "1","10","11","12","324001","34","4","411037","583",
    "A","B","I","Ii","Iii","Iv","M","O","P", "World Bank", "Institute Of Psychiatry", "Renewable Energy", "Horticulture And Floriculture",
    "Adb","Adm.Is & Erp","Admin","Aipscb","Ampri","Ap","Apcrda","Apiwa","Ar","Asm", "Govt. Of India", "Dnc Welfare", "Food Biotechnology Institute",
    "Ayush","Ball","Bbsr","Cea","Cimap","Civil","Cmd","Cvl", "Ce And As", "Manging Director", "Operative Bank Ltd", "Health Kerala Pmu",
    "De","Development & Monitoring","Dgp","Dhi","Dit","Dmc","Dst", "Social Sector P.W.Dte", "Communicable Diseases Jodhpur", "Operative Bank Ltd.",
    "Ecology & Environment","Ee R&B Peddapuram", "Operative Societies", "Dum Dum Subdivi", "Research And Management", "Operative Federation Ltd",
    "Fert","Fremaa","Frst","Frstry", "Op Corp. Ltd.", "Secretary", "Operative Society Ltd.", "Govt.Of India", "Resident Tamils", "P. W. Dte.",
    "Ghmc","Gifsa","Gm","Gmvn","Gr","Gvmp","Gvwv & Vsws","Gwmc", "Secretary", "Lawrenc", "Apepdcl", "Government Of Haryana", "Operative Bank Limited",
    "Ham","Hmda","Hod","Horticulture & Floriculture","Hpridc","Hq","I.","Ii N.B.M.C.&H.Campus Siliguri","Imd","Incois","Jntu",
    "Ktps", "Archives And Museums", "Commissioner", "Social Sector", "Social Sector P.W.Dte", "Government Of India", "Operative Federation Ltd.",
    "Lic","Lis & Enquiries", "Technology And Environment", "Dairying And Fisheries", "Gurazala Nagar Panchayat", "Government Of Uttarakhand",
    "Ma & Ud","Maha.","Master Plan&Lines","Mbma","Md","Mech","Mha","Mopng","Mord","Mos","Mphga","Msidc","Msme","Msrrda", "0Perative Federation Ltd.",
    "Nalco","Nbb","Nh","Nlr", "Servicemen Welfare", "Shipping And Waterways", "Doping Agency", "Operative Audit", "National Chemical Laboratory",
    "O&M","O&P&Mm Tirupati","Om", "Commercial Tax", "Gradens And Parks", "Kalna Highway Subdivi.", "Government Of India", "Family Courts", "V",
    "P&Mm","P.R.I","P.W.D","P.W.D.","Piu","Ppcl","Pri","Pur","Pwd","Pwdte", "Director", "Iisco Steel Plant", "Govt. Of Bihar", "Podili.", "Tb Dam",
    "Risl", "Transport", "Transport Commissionerate", "Op Bank Ltd", "Ndb Tenders", "Public Works Directorate", "University Of Mumbai", "Governance",
    "Scert","Se","Spmcil", "Operative Federation Ltd.", "Servicemens Corporation Limited", "South 24 Parganas", "Government Of Rajasthan", "District Court",
    "Tbp","Ts","Tsrtc","Tgsco","Ujvn","Upcl", "Operative Pharmacy Ltd", "Transmission", "Social Sector P.W.Dte.", "Patna University", "Government Of Meghalaya",
    "Vmrda", "Updcc Ltd.", "Operative Society Limited", "Operative Bank Ltd", "Operation", "Bokaro Steel Plant", "Govt.Of.Karnataka", "Chandra Research Institute",
    "Wbt","Wr","Wrd","Dhi","Mha","Bbsr","Nh","Mopng","Mos","Mord","Ppcl","Cmd","Md","Gm","Asm","Hq","Tsecl","Gmvn","Ujvn","Upcl", "Iisco Steel Plan",
    "Pwd","Risl","Gvmp","Dgp","Adb","Mp","Wbt","Nbb","Spmcil","Tn","Up","Ar","Dit","Hod","Fert","Scert","Wb","O","Dst","Mphga","Hpridc", "M Mpptcl Seoni",
    "Dmc","Msme","Vmrda","Pri","Gr","Msrrda","Tidcl","Jntu","Vsk","Lic","Pwdte","Tbp","Wrd","Imd","Nlr","Wr","Mbma","Ts","Tsrtc","Tgsco", "Wyra H.Q Khammam",
    "Rtpp","Gwmc","Frst","Ghmc","Frstry","Se","Ktps","Tnred","Hyd.","Cvl","Msidc","P&Mm","Mech","Hmda","1","10","11","12","324001","34","4","411037","583",
    "A","B","I","Ii","Iii","Iv","M","O","P","Adb","Adm.Is & Erp","Admin","Aipscb","Ampri","Ap","Apcrda","Apiwa","Ar","Asm","Ayush","Ball","Bbsr","Cea","Cimap","Civil","Cmd","Cvl",
    "De","Development & Monitoring","Dgp","Dhi","Dit","Dmc","Dst", "Operative Society Ltd.", "X", "Rourkela Steel Plant", "Operative Federation Ltd.", "Ysr Dist",
    "Ecology & Environment","Ee R&B Peddapuram", "Government Of Rajasthan", "Apmsidc", "Ii Pwd", "Cmo Head Quarters", "Durgapur Steel Plant", "Operative Society",
    "Fert","Fremaa","Frst","Frstry", "Restoration Society", "Conductor Laboratory", "Nuzvid", "Asansol Subdivi", "Developed And Hosted", "Civil Nshes", "Iii Pwd",
    "Ghmc","Gifsa","Gm","Gmvn","Gr","Gvmp","Gvwv & Vsws","Gwmc", "City Survey", "Ah And Aw", "Servicemen Welfare", "Taazgi Jharkhand Ki", "Ee Phmed  Khammam", "P.W. Directorate",
    "Ham","Hmda","Hod","Horticulture & Floriculture","Hpridc","Hq","I.","Ii N.B.M.C.&H.Campus Siliguri","Imd","Incois", "Government Of Chhattisgarh", "Op Society Ltd",
    "Ktps", "Secretariat", "City Company Limited", "Ichi Life Insurance", "Nidadavole", "Social Sector Pwd", "Technology And Environment", "Thermal",
    "Lic","Lis & Enquiries", "31 11:31:37.0", "Business Consortium", "E.G.Dist", "P.W.Dte", "P.W.Dte.", "Govt.Of.Karnataka.", "Se   I&Cad  Sangareddy", "Operative Federation Limited",
    "Ma & Ud","Maha.","Master Plan&Lines","Mbma","Md","Mech","Mha","Mopng","Mord","Mos","Mphga","Msidc","Msme","Msrrda", "Burdwan Nh Subdivi.", "Assam Secretariat",
    "Nalco","Nan","Nbb","Nh","Nlr", "Operative Bank Ltd", "Eluru", "Rajahmundry At Dowlaiswaram", "Apepdcl","P. W. Dte", "Works", "Div6", "Div5", "Adb Tender",
    "O&M","O&P&Mm Tirupati","Om", "W G Dt", "Aphmhidc", "Rws&S Kadapa", "Srbc Divn No.2", "Govt Of Ap", "Government Of Odisha", "Lakes", "Se R&B Balkampet",
    "P&Mm","P.R.I","P.W.D","P.W.D.","Piu","Ppcl","Pri","Pur","Pwd","Pwdte", "Windhoek", "Bhilai Steel Plant", "Se R&B Eluru", "Tscogfl", "Mdb Tenders",
    "Risl","Scert","Se","Spmcil", "Admin Material", "Public Work Directorate", "Vii", "Govt.Of.Karnataka", "Tsgenco", "Swachha Andhra Corporation", "P.W. Dte.",
    "Tbp","Ts","Tsrtc","Tgsco","Ujvn","Upcl", "M V Damsite", "P.W.Directorate", "Sri Mukatsar Sahib", "T", "Iv B", "Tidc Ltd", "Principal Secretary",
    "Vmrda","Wbt","Wr","Wrd" 
]

df["Location (clean)"] = df["Location (clean)"].apply(
    lambda x: "Nan" if x in junk_words else x
)

In [72]:
df.to_csv("full_dataset.csv", index=False, na_rep="NaN")

In [73]:
df.head()

,id,Organisation,Department,Location (raw),Location (clean),Org Name (Raw),Org Name (Clean),org_search
0,1,Airports Authority of India,Western Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
1,1,Airports Authority of India,North East Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
2,1,Airports Authority of India,Eastern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
3,1,Airports Authority of India,Southern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai
4,1,Airports Authority of India,Northern Region - AAI,Airports Authority of India,NaN,airports authority india,AAI,airports authority india aai